### ISSUE TITLE
Realm Works Import Button DnD 3.5e

### ISSUE THREAD

**Issue by Trellinane** [farling42/fvtt-import-realmworks#64]
I am not seeing the import button in the compendium tab when I a make a world under the DnD 3.5 SRD.  Does this module not work for that game system?  Thank you.

**Comment by farling42** [comment]
The module should work with all game systems.
Could you check that the module is enabled, and whether there are any errors reported in the console (open with F12) when you enter the world (or enable the module).

Which version of Foundry are you using?

**Comment by Trellinane** [comment]
I finally had a chance to check.

Foundry version is 9.269
Realm Works Importer is 1.23

The module is enabled and the only thing I see in the console that indicates any sort of warning is a message indicating:
disguise unreachable links: ready hook disguise-unreachable-links.mjs:51 

Still no Realm Works button on the Compendium tab.

**Comment by farling42** [comment]
I found the problem, it seems like it might be specific to the 3.5 SRD game system.

The hooks I use to get the button into the compendiums tab do not exist in the 3.5 SRD game system.

I have made a change so that it the button can't be placed at the top of the compendium tab then instead it will be placed at the bottom of the compendiums tab - and this seems to work with a world created for the 3.5 SRD game system.

This is available in version 1.24 for Foundry 9
