### ISSUE TITLE
Version 10 bombs on import

### ISSUE THREAD

**Issue by ajdude88** [farling42/fvtt-import-realmworks#72]
Hi,

I was using this in Foundry V9 and it worked perfectly.  With the move to v10 I installed the updated modules, but it pops an error when I try to import the RW export.    I host on Forge and thought maybe that was the issue, but I created a v10 local install and got a similar message, and then went back to v9 local and it worked again.  

An error right at the start of the world only happens when the realm-works module is active:

<img width="400" alt="Screenshot 2022-09-04 230837" src="https://user-images.githubusercontent.com/112839640/188353286-1ca15805-c5b1-4d07-8ef7-c2ce923828ee.png">

And when I try to import the RW Export: 
<img width="281" alt="Screenshot 2022-09-04 230612" src="https://user-images.githubusercontent.com/112839640/188353049-87619d44-c74b-4428-b144-35acdc9c3f1d.png">

Any thoughts?  Running Chrome on a Windows 11 PC if that matters.

**Comment by farling42** [comment]
What game system are you using this with? Regards,MartinOn 5 Sept 2022 04:11, ajdude88 ***@***.***> wrote:
Hi,
I was using this in Foundry V9 and it worked perfectly.  With the move to v10 I installed the updated modules, but it pops an error when I try to import the RW export.    I host on Forge and thought maybe that was the issue, but I created a v10 local install and got a similar message, and then went back to v9 local and it worked again.
An error right at the start of the world only happens when the realm-works module is active:

And when I try to import the RW Export:

Any thoughts?  Running Chrome on a Windows 11 PC if that matters.

**Comment by farling42** [comment]
It seems that V10 loads modules slightly differently, so this module was trying to access a file in the PF1 game system (regardless of the actual game system being used for the world).

The module has now been changed so that this will no longer happen.

**Comment by farling42** [comment]
This should be fixed in V2.4

**Comment by ajdude88** [comment]
Awesome, thanks dude, you are a game lifesaver!

To answer your first question, I am running DnD5e.  I figured it was Foundry versioning, because it worked fine on v9 locally.

Regards,
AJ

On Sep 5, 2022, at 6:21 AM, Martin ***@***.***> wrote:

﻿

This should be fixed in V2.4
